flask-basic-registration/project/models.py
# project/models.py


import datetime

from project import db, bcrypt


class User(db.Model):

    __tablename__ = "users"

    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(50), unique=True, nullable=False)
    password = db.Column(db.String(100), nullable=False)
    registered_on = db.Column(db.DateTime, nullable=False)
    admin = db.Column(db.Boolean, nullable=False, default=False)
    confirmed = db.Column(db.Boolean, nullable=False, default=False)
    confirmed_on = db.Column(db.DateTime, nullable=True)

    def __init__(self, email, password, confirmed,
                 paid=False, admin=False, confirmed_on=None):
        self.email = email
        self.password = bcrypt.generate_password_hash(password)
        self.registered_on = datetime.datetime.now()
        self.admin = admin
        self.confirmed = confirmed
        self.confirmed_on = confirmed_on

    def is_authenticated(self):
        return True

    def is_active(self):
        return True

    def is_anonymous(self):
        return False

    def get_id(self):
        return self.id

    def __repr__(self):
        return '<email {}'.format(self.email)

flask-basic-registration/project/models/user.py
# project/user.py


import datetime

from project import db, bcrypt


class User(db.Model):
    __tablename__ = "users"

    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(50), unique=True, nullable=False)
    password = db.Column(db.String(100), nullable=False)
    registered_on = db.Column(db.DateTime, nullable=False)
    admin = db.Column(db.Boolean, nullable=False, default=False)
    confirmed = db.Column(db.Boolean, nullable=False, default=False)
    confirmed_on = db.Column(db.DateTime, nullable=True)

    def __init__(self, email, password, confirmed,
                 paid=False, admin=False, confirmed_on=None):
        self.email = email
        self.password = bcrypt.generate_password_hash(password)
        self.registered_on = datetime.datetime.now()
        self.admin = admin
        self.confirmed = confirmed
        self.confirmed_on = confirmed_on

    def is_authenticated(self):
        return True

    def is_active(self):
        return True

    def is_anonymous(self):
        return False

    def get_id(self):
        return self.id

    def __repr__(self):
        return '<email {}'.format(self.email)

flask-basic-registration/project/user/forms.py
# project/user/forms.py


from flask_wtf import Form
from wtforms import TextField, PasswordField
from wtforms.validators import DataRequired, Email, Length, EqualTo

from project.models.user import User


class LoginForm(Form):
    email = TextField('email', validators=[DataRequired(), Email()])
    password = PasswordField('password', validators=[DataRequired()])


class ResetForm(Form):
    email = TextField('email', validators=[DataRequired(), Email()])


class RegisterForm(Form):
    email = TextField(
        'email',
        validators=[DataRequired(), Email(message=None), Length(min=6, max=40)])
    password = PasswordField(
        'password',
        validators=[DataRequired(), Length(min=6, max=25)]
    )
    confirm = PasswordField(
        'Repeat password',
        validators=[
            DataRequired(),
            EqualTo('password', message='Passwords must match.')
        ]
    )

    def validate(self):
        initial_validation = super(RegisterForm, self).validate()
        if not initial_validation:
            return False
        user = User.query.filter_by(email=self.email.data).first()
        if user:
            self.email.errors.append("Email already registered")
            return False
        return True


class ChangePasswordForm(Form):
    password = PasswordField(
        'password',
        validators=[DataRequired(), Length(min=6, max=25)]
    )
    confirm = PasswordField(
        'Repeat password',
        validators=[
            DataRequired(),
            EqualTo('password', message='Passwords must match.')
        ]
    )

flask-basic-registration/project/__init__.py
# project/__init__.py


#################
#### imports ####
#################

import os

from flask import Flask, render_template
from flask_mail import Mail

try:
    from flask.ext.debugtoolbar import DebugToolbarExtension
    from flask.ext.sqlalchemy import SQLAlchemy
    from flask.ext.login import LoginManager
    from flask.ext.bcrypt import Bcrypt
except:
    from flask_debugtoolbar import DebugToolbarExtension
    from flask_sqlalchemy import SQLAlchemy
    from flask_login import LoginManager
    from flask_bcrypt import Bcrypt

################
#### config ####
################

app = Flask(__name__)

try:
    app.config.from_object(os.environ['APP_SETTINGS'])
except:
    from .config import DevelopmentConfig

    app.config.from_object(DevelopmentConfig)

####################
#### extensions ####
####################

login_manager = LoginManager()
login_manager.init_app(app)
bcrypt = Bcrypt(app)
mail = Mail(app)
toolbar = DebugToolbarExtension(app)
db = SQLAlchemy(app)

####################
#### blueprints ####
####################

from project.main.views import main_blueprint
from project.user.views import user_blueprint

app.register_blueprint(main_blueprint)
app.register_blueprint(user_blueprint)

####################
#### flask-login ####
####################

from project.models.user import User

login_manager.login_view = "user.login"
login_manager.login_message_category = "danger"


@login_manager.user_loader
def load_user(user_id):
    return User.query.filter(User.id == int(user_id)).first()


########################
#### error handlers ####
########################

@app.errorhandler(403)
def forbidden_page(error):
    return render_template("errors/403.html"), 403


@app.errorhandler(404)
def page_not_found(error):
    return render_template("errors/404.html"), 404


@app.errorhandler(500)
def server_error_page(error):
    return render_template("errors/500.html"), 500

flask-basic-registration/project/main/views.py
# project/main/views.py


#################
#### imports ####
#################

from flask import render_template, Blueprint
from flask_login import login_required

################
#### config ####
################


main_blueprint = Blueprint('main', __name__, )


################
#### routes ####
################

@main_blueprint.route('/')
@login_required
def home():
    return render_template('main/index.html')

flask-basic-registration/project/user/views.py
# project/user/views.py


#################
#### imports ####
#################
import datetime

from flask import render_template, Blueprint, url_for, \
    redirect, flash, request
from flask_login import login_user, logout_user, \
    login_required, current_user

from project.models.user import User
# from project.email import send_email
from project import db, bcrypt
from .forms import LoginForm, RegisterForm, ChangePasswordForm, ResetForm

from project.tools.token import generate_confirmation_token, confirm_token
from project.tools.email import send_email
from project.tools.decorators import check_confirmed

################
#### config ####
################

user_blueprint = Blueprint('user', __name__, )


################
#### routes ####
################

@user_blueprint.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm(request.form)
    if form.validate_on_submit():
        user = User(
            email=form.email.data,
            password=form.password.data,
            confirmed=False
        )
        db.session.add(user)
        db.session.commit()

        token = generate_confirmation_token(user.email)
        confirm_url = url_for('user.confirm_email', token=token, _external=True)
        html = render_template('user/activate.html', confirm_url=confirm_url)
        subject = "Please confirm your email"
        send_email(user.email, subject, html)

        login_user(user)

        flash('A confirmation email has been sent via email.', 'success')
        # return redirect(url_for("main.home"))
        return redirect(url_for("user.unconfirmed"))

    return render_template('user/register.html', form=form)


@user_blueprint.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm(request.form)
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(
                user.password, request.form['password']):
            login_user(user)
            flash('Welcome.', 'success')
            return redirect(url_for('main.home'))
        else:
            flash('Invalid email and/or password.', 'danger')
            return render_template('user/login.html', form=form)
    return render_template('user/login.html', form=form)


@user_blueprint.route('/logout')
@login_required
def logout():
    logout_user()
    flash('You were logged out.', 'success')
    return redirect(url_for('user.login'))


@user_blueprint.route('/profile', methods=['GET', 'POST'])
@login_required
@check_confirmed
def profile():
    form = ChangePasswordForm(request.form)
    if form.validate_on_submit():
        user = User.query.filter_by(email=current_user.email).first()
        if user:
            user.password = bcrypt.generate_password_hash(form.password.data)
            db.session.commit()
            flash('Password successfully changed.', 'success')
            subject = "your have change password !"
            html = "你正在修改你的密码，且已经修改成功!"
            send_email(current_user.email, subject, html)
            flash('A new confirmation email has been sent.', 'success')
            return redirect(url_for('user.profile'))
        else:
            flash('Password change was unsuccessful.', 'danger')
            return redirect(url_for('user.profile'))
    return render_template('user/profile.html', form=form)


@user_blueprint.route('/confirm/<token>')
@login_required
def confirm_email(token):
    try:
        email = confirm_token(token)
    except:
        flash('The confirmation link is invalid or has expired.', 'danger')
    user = User.query.filter_by(email=email).first_or_404()
    if user.confirmed:
        flash('Account already confirmed. Please login.', 'success')
    else:
        user.confirmed = True
        user.confirmed_on = datetime.datetime.now()
        db.session.add(user)
        db.session.commit()
        flash('You have confirmed your account. Thanks!', 'success')
    return redirect(url_for('main.home'))


@user_blueprint.route('/unconfirmed')
@login_required
def unconfirmed():
    if current_user.confirmed:
        return redirect('main.home')
    flash('Please confirm your account!', 'warning')
    return render_template('user/unconfirmed.html')


@user_blueprint.route('/resend')
@login_required
def resend_confirmation():
    token = generate_confirmation_token(current_user.email)
    confirm_url = url_for('user.confirm_email', token=token, _external=True)
    html = render_template('user/activate.html', confirm_url=confirm_url)
    subject = "Please confirm your email"
    # html = "这是一个测试邮件！但经常被拦截。"
    send_email(current_user.email, subject, html)
    flash('A new confirmation email has been sent.', 'success')
    return redirect(url_for('user.unconfirmed'))


@user_blueprint.route('/reset/', methods=['GET', 'POST'])
def reset_password_by_email():
    form = ResetForm(request.form)
    if request.method == "GET":
        return render_template("user/reset_input_email.html", form=form)
    if request.method == "POST":
        try:
            email = form.email.data
        except:
            flash('we need your email address!', 'danger')
        if form.validate_on_submit():
            user = User.query.filter_by(email=email).first_or_404()
            if user.confirmed:
                token = generate_confirmation_token(user.email)
                reset_url = url_for('user.change_password_by_email', token=token, _external=True)
                html = render_template('user/activate.html', confirm_url=reset_url)
                subject = "reset your password by url!"
                send_email(email, subject, html)
                flash('reset password email already sended. please check!', 'success')
            else:
                flash('check your account!', 'danger')
            return redirect(url_for('user.login'))


@user_blueprint.route('/change/', methods=['GET', 'POST'])
def change_password_by_email():
    form_login = LoginForm(request.form)
    form_reset = ChangePasswordForm(request.form)
    if request.method == "GET":
        token = request.values.get("token")
        if token:
            try:
                email = confirm_token(token)
                User.query.filter_by(email=email).first_or_404()
            except:
                flash('The confirmation link is invalid or has expired.', 'danger')
            return render_template("user/reset_input_password.html", form=form_reset)
    if request.method == "POST":
        if form_reset.validate_on_submit():
            token = request.values.get("token")
            print("headers:", request.headers.values())
            email = confirm_token(token)
            user = User.query.filter_by(email=email).first_or_404()
            if user:
                user.password = bcrypt.generate_password_hash(form_reset.password.data)
                db.session.commit()
                flash('Password successfully changed.', 'success')
                subject = "you have change password !"
                html = "你已成功修改密码，请注意密码安全!"
                send_email(email, subject, html)
                flash('A new confirmation email has been sent.', 'success')
                return redirect(url_for('user.profile'))
            else:
                flash('Password change was unsuccessful.', 'danger')
                return redirect(url_for('user.profile'))
        return render_template('user/profile.html', form=form_login)

flask-basic-registration/project/templates/_base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Flask User Management</title>
    <!-- meta -->
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <!-- styles -->
    <link href="http://maxcdn.bootstrapcdn.com/bootswatch/3.2.0/yeti/bootstrap.min.css" rel="stylesheet" media="screen">
    <link href="{{ url_for('static', filename='main.css') }}" rel="stylesheet" media="screen">
    {% block css %}{% endblock %}
</head>
<body>

{% include "navigation.html" %}

<div class="container">

    <br>

    <!-- messages -->
    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            <div class="row">
                <div class="col-md-12">
                    {% for category, message in messages %}
                        <div class="alert alert-{{ category }}">
                            <a class="close" title="Close" href="#" data-dismiss="alert">&times;</a>
                            {{ message }}
                        </div>
                    {% endfor %}
                </div>
            </div>
        {% endif %}
    {% endwith %}

    <!-- child template -->
    {% block content %}{% endblock %}

    <br>

    <!-- errors -->
    {% if error %}
        <p class="error"><strong>Error:</strong> {{ error }}</p>
    {% endif %}

</div>

<!-- scripts -->
<script src="https://code.jquery.com/jquery-2.1.1.min.js" type="text/javascript"></script>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js" type="text/javascript"></script>
<script src="{{ url_for('static', filename='main.js') }}" type="text/javascript"></script>
{% block js %}{% endblock %}

</body>
</html>

flask-basic-registration/project/templates/navigation.html
<!-- Navigation -->
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ url_for('main.home') }}">Flask-User-Management</a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                {% if current_user.confirmed and current_user.is_authenticated %}
                    <li><a href="{{ url_for('user.profile') }}">Profile</a></li>
                {% elif current_user.is_authenticated %}
                    <li><a href="{{ url_for('user.unconfirmed') }}">Confirm</a></li>
                {% endif %}
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if current_user.is_authenticated %}
                    <li><a href="{{ url_for('user.logout') }}">Logout</a></li>
                {% else %}
                    <li><a href="{{ url_for('user.register') }}">Sign up</a></li>
                    <li><a href="{{ url_for('user.login') }}"><span class="glyphicon glyphicon-user"></span>&nbsp;Login</a>
                    </li>
                {% endif %}
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>