flask-basic-registration/project/models.py
# project/models.py


import datetime

from project import db, bcrypt


class User(db.Model):

    __tablename__ = "users"

    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(50), unique=True, nullable=False)
    password = db.Column(db.String(100), nullable=False)
    registered_on = db.Column(db.DateTime, nullable=False)
    admin = db.Column(db.Boolean, nullable=False, default=False)
    confirmed = db.Column(db.Boolean, nullable=False, default=False)
    confirmed_on = db.Column(db.DateTime, nullable=True)

    def __init__(self, email, password, confirmed,
                 paid=False, admin=False, confirmed_on=None):
        self.email = email
        self.password = bcrypt.generate_password_hash(password)
        self.registered_on = datetime.datetime.now()
        self.admin = admin
        self.confirmed = confirmed
        self.confirmed_on = confirmed_on

    def is_authenticated(self):
        return True

    def is_active(self):
        return True

    def is_anonymous(self):
        return False

    def get_id(self):
        return self.id

    def __repr__(self):
        return '<email {}'.format(self.email)

flask-basic-registration/project/models/user.py
# project/user.py


import datetime

from project import db, bcrypt


class User(db.Model):
    __tablename__ = "users"

    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(50), unique=True, nullable=False)
    password = db.Column(db.String(100), nullable=False)
    registered_on = db.Column(db.DateTime, nullable=False)
    admin = db.Column(db.Boolean, nullable=False, default=False)
    confirmed = db.Column(db.Boolean, nullable=False, default=False)
    confirmed_on = db.Column(db.DateTime, nullable=True)

    def __init__(self, email, password, confirmed,
                 paid=False, admin=False, confirmed_on=None):
        self.email = email
        self.password = bcrypt.generate_password_hash(password)
        self.registered_on = datetime.datetime.now()
        self.admin = admin
        self.confirmed = confirmed
        self.confirmed_on = confirmed_on

    def is_authenticated(self):
        return True

    def is_active(self):
        return True

    def is_anonymous(self):
        return False

    def get_id(self):
        return self.id

    def __repr__(self):
        return '<email {}'.format(self.email)

flask-basic-registration/project/user/forms.py
# project/user/forms.py


from flask_wtf import Form
from wtforms import TextField, PasswordField
from wtforms.validators import DataRequired, Email, Length, EqualTo

from project.models.user import User


class LoginForm(Form):
    email = TextField('email', validators=[DataRequired(), Email()])
    password = PasswordField('password', validators=[DataRequired()])


class ResetForm(Form):
    email = TextField('email', validators=[DataRequired(), Email()])


class RegisterForm(Form):
    email = TextField(
        'email',
        validators=[DataRequired(), Email(message=None), Length(min=6, max=40)])
    password = PasswordField(
        'password',
        validators=[DataRequired(), Length(min=6, max=25)]
    )
    confirm = PasswordField(
        'Repeat password',
        validators=[
            DataRequired(),
            EqualTo('password', message='Passwords must match.')
        ]
    )

    def validate(self):
        initial_validation = super(RegisterForm, self).validate()
        if not initial_validation:
            return False
        user = User.query.filter_by(email=self.email.data).first()
        if user:
            self.email.errors.append("Email already registered")
            return False
        return True


class ChangePasswordForm(Form):
    password = PasswordField(
        'password',
        validators=[DataRequired(), Length(min=6, max=25)]
    )
    confirm = PasswordField(
        'Repeat password',
        validators=[
            DataRequired(),
            EqualTo('password', message='Passwords must match.')
        ]
    )

flask-basic-registration/project/__init__.py
# project/__init__.py


#################
#### imports ####
#################

import os

from flask import Flask, render_template
from flask_mail import Mail

try:
    from flask.ext.debugtoolbar import DebugToolbarExtension
    from flask.ext.sqlalchemy import SQLAlchemy
    from flask.ext.login import LoginManager
    from flask.ext.bcrypt import Bcrypt
except:
    from flask_debugtoolbar import DebugToolbarExtension
    from flask_sqlalchemy import SQLAlchemy
    from flask_login import LoginManager
    from flask_bcrypt import Bcrypt

################
#### config ####
################

app = Flask(__name__)

try:
    app.config.from_object(os.environ['APP_SETTINGS'])
except:
    from .config import DevelopmentConfig

    app.config.from_object(DevelopmentConfig)

####################
#### extensions ####
####################

login_manager = LoginManager()
login_manager.init_app(app)
bcrypt = Bcrypt(app)
mail = Mail(app)
toolbar = DebugToolbarExtension(app)
db = SQLAlchemy(app)

####################
#### blueprints ####
####################

from project.main.views import main_blueprint
from project.user.views import user_blueprint

app.register_blueprint(main_blueprint)
app.register_blueprint(user_blueprint)

####################
#### flask-login ####
####################

from project.models.user import User

login_manager.login_view = "user.login"
login_manager.login_message_category = "danger"


@login_manager.user_loader
def load_user(user_id):
    return User.query.filter(User.id == int(user_id)).first()


########################
#### error handlers ####
########################

@app.errorhandler(403)
def forbidden_page(error):
    return render_template("errors/403.html"), 403


@app.errorhandler(404)
def page_not_found(error):
    return render_template("errors/404.html"), 404


@app.errorhandler(500)
def server_error_page(error):
    return render_template("errors/500.html"), 500

flask-basic-registration/project/main/views.py
# project/main/views.py


#################
#### imports ####
#################

from flask import render_template, Blueprint
from flask_login import login_required

################
#### config ####
################


main_blueprint = Blueprint('main', __name__, )


################
#### routes ####
################

@main_blueprint.route('/')
@login_required
def home():
    return render_template('main/index.html')

flask-basic-registration/project/user/views.py
# project/user/views.py


#################
#### imports ####
#################
import datetime

from flask import render_template, Blueprint, url_for, \
    redirect, flash, request
from flask_login import login_user, logout_user, \
    login_required, current_user

from project.models.user import User
# from project.email import send_email
from project import db, bcrypt
from .forms import LoginForm, RegisterForm, ChangePasswordForm, ResetForm

from project.tools.token import generate_confirmation_token, confirm_token
from project.tools.email import send_email
from project.tools.decorators import check_confirmed

################
#### config ####
################

user_blueprint = Blueprint('user', __name__, )


################
#### routes ####
################

@user_blueprint.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm(request.form)
    if form.validate_on_submit():
        user = User(
            email=form.email.data,
            password=form.password.data,
            confirmed=False
        )
        db.session.add(user)
        db.session.commit()

        token = generate_confirmation_token(user.email)
        confirm_url = url_for('user.confirm_email', token=token, _external=True)
        html = render_template('user/activate.html', confirm_url=confirm_url)
        subject = "Please confirm your email"
        send_email(user.email, subject, html)

        login_user(user)

        flash('A confirmation email has been sent via email.', 'success')
        # return redirect(url_for("main.home"))
        return redirect(url_for("user.unconfirmed"))

    return render_template('user/register.html', form=form)


@user_blueprint.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm(request.form)
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(
                user.password, request.form['password']):
            login_user(user)
            flash('Welcome.', 'success')
            return redirect(url_for('main.home'))
        else:
            flash('Invalid email and/or password.', 'danger')
            return render_template('user/login.html', form=form)
    return render_template('user/login.html', form=form)


@user_blueprint.route('/logout')
@login_required
def logout():
    logout_user()
    flash('You were logged out.', 'success')
    return redirect(url_for('user.login'))


@user_blueprint.route('/profile', methods=['GET', 'POST'])
@login_required
@check_confirmed
def profile():
    form = ChangePasswordForm(request.form)
    if form.validate_on_submit():
        user = User.query.filter_by(email=current_user.email).first()
        if user:
            user.password = bcrypt.generate_password_hash(form.password.data)
            db.session.commit()
            flash('Password successfully changed.', 'success')
            subject = "your have change password !"
            html = "你正在修改你的密码，且已经修改成功!"
            send_email(current_user.email, subject, html)
            flash('A new confirmation email has been sent.', 'success')
            return redirect(url_for('user.profile'))
        else:
            flash('Password change was unsuccessful.', 'danger')
            return redirect(url_for('user.profile'))
    return render_template('user/profile.html', form=form)


@user_blueprint.route('/confirm/<token>')
@login_required
def confirm_email(token):
    try:
        email = confirm_token(token)
    except:
        flash('The confirmation link is invalid or has expired.', 'danger')
    user = User.query.filter_by(email=email).first_or_404()
    if user.confirmed:
        flash('Account already confirmed. Please login.', 'success')
    else:
        user.confirmed = True
        user.confirmed_on = datetime.datetime.now()
        db.session.add(user)
        db.session.commit()
        flash('You have confirmed your account. Thanks!', 'success')
    return redirect(url_for('main.home'))


@user_blueprint.route('/unconfirmed')
@login_required
def unconfirmed():
    if current_user.confirmed:
        return redirect('main.home')
    flash('Please confirm your account!', 'warning')
    return render_template('user/unconfirmed.html')


@user_blueprint.route('/resend')
@login_required
def resend_confirmation():
    token = generate_confirmation_token(current_user.email)
    confirm_url = url_for('user.confirm_email', token=token, _external=True)
    html = render_template('user/activate.html', confirm_url=confirm_url)
    subject = "Please confirm your email"
    # html = "这是一个测试邮件！但经常被拦截。"
    send_email(current_user.email, subject, html)
    flash('A new confirmation email has been sent.', 'success')
    return redirect(url_for('user.unconfirmed'))


@user_blueprint.route('/reset/', methods=['GET', 'POST'])
def reset_password_by_email():
    form = ResetForm(request.form)
    if request.method == "GET":
        return render_template("user/reset_input_email.html", form=form)
    if request.method == "POST":
        try:
            email = form.email.data
        except:
            flash('we need your email address!', 'danger')
        if form.validate_on_submit():
            user = User.query.filter_by(email=email).first_or_404()
            if user.confirmed:
                token = generate_confirmation_token(user.email)
                reset_url = url_for('user.change_password_by_email', token=token, _external=True)
                html = render_template('user/activate.html', confirm_url=reset_url)
                subject = "reset your password by url!"
                send_email(email, subject, html)
                flash('reset password email already sended. please check!', 'success')
            else:
                flash('check your account!', 'danger')
            return redirect(url_for('user.login'))


@user_blueprint.route('/change/', methods=['GET', 'POST'])
def change_password_by_email():
    form_login = LoginForm(request.form)
    form_reset = ChangePasswordForm(request.form)
    if request.method == "GET":
        token = request.values.get("token")
        if token:
            try:
                email = confirm_token(token)
                User.query.filter_by(email=email).first_or_404()
            except:
                flash('The confirmation link is invalid or has expired.', 'danger')
            return render_template("user/reset_input_password.html", form=form_reset)
    if request.method == "POST":
        if form_reset.validate_on_submit():
            token = request.values.get("token")
            print("headers:", request.headers.values())
            email = confirm_token(token)
            user = User.query.filter_by(email=email).first_or_404()
            if user:
                user.password = bcrypt.generate_password_hash(form_reset.password.data)
                db.session.commit()
                flash('Password successfully changed.', 'success')
                subject = "you have change password !"
                html = "你已成功修改密码，请注意密码安全!"
                send_email(email, subject, html)
                flash('A new confirmation email has been sent.', 'success')
                return redirect(url_for('user.profile'))
            else:
                flash('Password change was unsuccessful.', 'danger')
                return redirect(url_for('user.profile'))
        return render_template('user/profile.html', form=form_login)

flask-basic-registration/project/templates/user/activate.html
<p>Welcome! Thanks for signing up. Please follow this link to activate your account:</p>
<p><a href="{{ confirm_url }}">{{ confirm_url }}</a></p>
<br>
<p>Cheers!</p>

flask-basic-registration/project/templates/user/login.html
{% extends "_base.html" %}

{% block content %}

    <h1>Please login</h1>
    <br>
    <form class="form-login" role="form" method="post" action="">
        {{ form.csrf_token }}
        <p>
            {{ form.email(placeholder="email") }}
            <span class="error">
      {% if form.email.errors %}
          {% for error in form.email.errors %}
              {{ error }}
          {% endfor %}
      {% endif %}
    </span>
        </p>
        <p>
            {{ form.password(placeholder="password") }}
            <span class="error">
      {% if form.password.errors %}
          {% for error in form.password.errors %}
              {{ error }}
          {% endfor %}
      {% endif %}
    </span>
        </p>
        <button class="btn btn-success" type="submit">Sign in!</button>
        <br><br>
        <p>Need to <a href="/register">Register</a>?</p>
        <p>Forget Password to <a href="/reset">Reset Password</a>?</p>

    </form>

{% endblock %}

flask-basic-registration/project/templates/user/profile.html
{% extends "_base.html" %}

{% block content %}

    <h1>Your Profile</h1>
    <br>

    {% if current_user.is_authenticated() %}
        <p>Email: {{ current_user.email }}</p>
    {% endif %}

    <h2>Change Password</h2>
    <br>
    <form class="form-reset" role="form" method="post" action="">
        {{ form.csrf_token }}
        <p>
            {{ form.password(placeholder="password") }}
            <span class="error">
      {% if form.password.errors %}
          {% for error in form.password.errors %}
              {{ error }}
          {% endfor %}
      {% endif %}
    </span>
        </p>
        <p>
            {{ form.confirm(placeholder="confirm") }}
            <span class="error">
      {% if form.confirm.errors %}
          {% for error in form.confirm.errors %}
              {{ error }}
          {% endfor %}
      {% endif %}
    </span>
        </p>
        <button class="btn btn-success" type="submit">Update</button>
    </form>


{% endblock %}

flask-basic-registration/project/templates/user/register.html
{% extends "_base.html" %}

{% block content %}

    <h1>Please Register</h1>
    <br>
    <form class="form-signin" role="form" method="post" action="">
        {{ form.csrf_token }}
        {{ form.email(placeholder="email") }}
        <span class="error">
      {% if form.email.errors %}
          {% for error in form.email.errors %}
              {{ error }}
          {% endfor %}
      {% endif %}
    </span>
        </p>
        <p>
            {{ form.password(placeholder="password") }}
            <span class="error">
      {% if form.password.errors %}
          {% for error in form.password.errors %}
              {{ error }}
          {% endfor %}
      {% endif %}
    </span>
        </p>
        <p>
            {{ form.confirm(placeholder="confirm") }}
            <span class="error">
      {% if form.confirm.errors %}
          {% for error in form.confirm.errors %}
              {{ error }}
          {% endfor %}
      {% endif %}
    </span>
        </p>
        <button class="btn btn-success" type="submit">Register!</button>
        <br><br>
        <p>Already have an account? <a href="/login">Sign in</a>.</p>
    </form>

{% endblock %}

flask-basic-registration/project/templates/user/reset_input_email.html
{% extends "_base.html" %}

{% block content %}

    <h1>Please login</h1>
    <br>
    <form class="form-login" role="form" method="post" action="">
        {{ form.csrf_token }}
        <p>
            {{ form.email(placeholder="email") }}
            <span class="error">
      {% if form.email.errors %}
          {% for error in form.email.errors %}
              {{ error }}
          {% endfor %}
      {% endif %}
    </span>
        </p>
        <p>
        </p>
        <button class="btn btn-success" type="submit">Reset Password!</button>
        <br><br>
        <p>Need to <a href="/register">Register</a>?</p>

    </form>

{% endblock %}

flask-basic-registration/project/templates/user/reset_input_password.html
{% extends "_base.html" %}

{% block content %}

    <h1>Reset Your Password</h1>
    <br>

    <form class="form-reset" role="form" method="post" action="">
        <input type="hidden" name="_method" value="put"/>
        {{ form.csrf_token }}
        <p>
            {{ form.password(placeholder="password") }}
            <span class="error">
      {% if form.password.errors %}
          {% for error in form.password.errors %}
              {{ error }}
          {% endfor %}
      {% endif %}
    </span>
        </p>
        <p>
            {{ form.confirm(placeholder="confirm") }}
            <span class="error">
      {% if form.confirm.errors %}
          {% for error in form.confirm.errors %}
              {{ error }}
          {% endfor %}
      {% endif %}
    </span>
        </p>
        <button class="btn btn-success" type="submit">Reset</button>
    </form>

{% endblock %}

flask-basic-registration/project/templates/user/unconfirmed.html
{% extends "_base.html" %}

{% block content %}

    <h1>Welcome!</h1>
    <br>
    <p>You have not confirmed your account. Please check your inbox (and your spam folder) - you should have received an
        email with a confirmation link.</p>
    <p>Didn't get the email? <a href="{{ url_for('user.resend_confirmation') }}">Resend</a>.</p>

{% endblock %}